### ISSUE TITLE
Day 19 missing from index

### ISSUE THREAD

**Issue by ghost** [Yakvi/handmade-hero-notes#3]
Looks like Day 19 is missing form the index

See here:
https://github.com/Yakvi/handmade-hero-notes/blob/ad7a5870e007687d43409d9e62314417e28994ee/index.md.html#L119

Thanks for your work on this!

**Comment by rby90** [comment]
Created a pull request for fix

https://github.com/Yakvi/handmade-hero-notes/pull/4

**Comment by Yakvi** [comment]
Thank you for the notice! I updated the `md.html` index.
