### ISSUE TITLE
Link to Removing CRT doesn't work.

### ISSUE THREAD

**Issue by RomanADavis** [Yakvi/handmade-hero-notes#7]
See the bottom of the page, here: https://yakvi.github.io/handmade-hero-notes/html/day16.html

Consider replacing with this: https://hero.handmade.network/forums/code-discussion/t/94-guide_-_how_to_avoid_c_c++_runtime_on_windows

**Comment by Yakvi** [comment]
Thank you! Both inline and the end-of-page links should now be fixed. It was indeed the link I originally intended to use!
